//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBook()
        {
            this.tblBookDetails = new HashSet<tblBookDetail>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Catagories { get; set; }
        public string Place { get; set; }
        public System.DateTime AddDate { get; set; }
        public string CoverPicture { get; set; }
        public string Status { get; set; }
        public string InstanceStatus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookDetail> tblBookDetails { get; set; }
    }
}
