//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBorrow
    {
        public int ID { get; set; }
        public string BorrowerEmail { get; set; }
        public string BookSubID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int ExtendNumber { get; set; }
        public bool IsEnd { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblBookDetail tblBookDetail { get; set; }
    }
}
